import { StrictMode, useEffect, useState } from 'react';
import { Bookmark, ChevronDown, Filter, MessageCircle, Pencil, Search, X } from 'lucide-react';
import './styles.css';

type Issue = { id:number; title:string; body:string; difficulty:string; difficulty_score:number; required_skills:string[]; technologies:string[]; repository:string; language:string; comments:number; url:string };
type Profile = { username:string; avatar_url:string; progress_score:number; completed_count:number };
type Progress = { contributions:Array<{id:number; title:string; repository:string; state:string; pr_url:string | null}> };
const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
const avatar = 'https://www.figma.com/api/mcp/asset/48adeab7-a22e-41ac-9ec6-d8415a001492.png';
async function get<T>(path:string):Promise<T> { const response = await fetch(`${API}${path}`); if (!response.ok) throw new Error('API request failed'); return response.json(); }

function App() {
  const [profile, setProfile] = useState<Profile | null>(null); const [issues, setIssues] = useState<Issue[]>([]); const [progress, setProgress] = useState<Progress>({contributions:[]}); const [query, setQuery] = useState(''); const [tab, setTab] = useState('SkillIssues'); const [selected, setSelected] = useState<Issue | null>(null); const [saved, setSaved] = useState<number[]>([]); const [error, setError] = useState('');
  async function loadIssues(search = '') { try { setIssues(await get<Issue[]>(`/issues?limit=8${search ? `&search=${encodeURIComponent(search)}` : ''}`)); } catch { setError('Start the API with docker compose up --build.'); } }
  useEffect(() => { Promise.all([get<Profile>('/me'), get<Issue[]>('/issues?limit=8'), get<Progress>('/progress')]).then(([user, list, currentProgress]) => { setProfile(user); setIssues(list); setProgress(currentProgress); }).catch(() => setError('Start the API with docker compose up --build.')); }, []);
  async function startChallenge() { if (!selected) return; await fetch(`${API}/contributions`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({issue_id:selected.id})}); setSelected(null); }
  if (error) return <main className="center"><h1>SkillIssues is offline</h1><p>{error}</p></main>;
  if (!profile) return <main className="center"><p>Loading SkillIssues...</p></main>;
  return <main className="web-home">
    {/* BRAND HEADER: change wordmark spacing and tagline here when the brand direction changes. */}
    <header className="web-header"><div className="wordmark">SkillIssues<span>You Have the Skills. We Have the Issues.</span></div></header>
    {/* SEARCH STRIP: filtering stays in one control row for easy redesign. */}
    <form className="web-search" onSubmit={(event) => { event.preventDefault(); loadIssues(query); }}><Search size={15}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Issues on JavaScript"/><button type="button" onClick={() => { setQuery(''); loadIssues(); }}>clear</button><button type="button" className="filter-button" title="Filters"><Filter size={13}/></button><button className="search-submit">Search</button></form>
    <section className="web-grid">
      {/* ISSUE FEED: cards use small semantic atoms so labels, badges, and actions can be rethemed independently. */}
      <div className="web-feed"><nav className="web-tabs">{['SkillIssues','Saved','Submissions'].map((item) => <button key={item} className={tab===item?'active':''} onClick={() => setTab(item)}>{item} <b>{item==='SkillIssues'?issues.length:item==='Saved'?saved.length:progress.contributions.length}</b></button>)}</nav><div className="feed-title"><h1>{tab}</h1><span>{tab==='SkillIssues'?'Skill based recommendations':tab==='Saved'?'Your saved issues':'Your current submissions'}</span></div><div className="issue-feed">{tab==='Submissions' ? (progress.contributions.length ? progress.contributions.map((submission) => <article className="web-issue" key={submission.id}><div className="issue-main"><div><h2>{submission.title}</h2><p>{submission.repository}</p></div><span className="atom action">{submission.state}</span></div><div className="issue-meta"><span className="atom">{submission.pr_url ? 'PR attached' : 'Not submitted'}</span></div></article>) : <p className="empty-feed">No submissions yet. Start a challenge from SkillIssues.</p>) : (tab==='Saved'?issues.filter((issue) => saved.includes(issue.id)):issues).map((issue) => <article className="web-issue" key={issue.id} onClick={() => setSelected(issue)}><div className="issue-main"><div><h2>{issue.title}</h2><p>{issue.repository}</p></div><span className={`difficulty ${issue.difficulty.toLowerCase()}`}>{issue.difficulty}</span></div><div className="issue-meta"><div className="atom-row"><span className="atom">{issue.language || 'Open source'}</span><span className="atom">{issue.difficulty_score}/10</span><span className="atom"><MessageCircle size={11}/>{issue.comments || 0}</span></div><div className="atom-row"><span className="atom light">{issue.technologies?.[0] || 'Issue'}</span><button className="atom action" onClick={(event) => { event.stopPropagation(); setSelected(issue); }}>View Issue</button><button className="save-button" title="Save issue" onClick={(event) => { event.stopPropagation(); setSaved((current) => current.includes(issue.id) ? current.filter((id) => id !== issue.id) : [...current, issue.id]); }}><Bookmark size={14} fill={saved.includes(issue.id) ? 'currentColor' : 'none'}/></button></div></div></article>)}</div></div>
      {/* PROFILE RAIL: compact identity panel from the supplied reference screenshots. */}
      <aside className="web-profile"><img src={avatar} alt="Max profile"/><h2>Max!!</h2><p className="profile-handle">@dizzbliss</p><p className="profile-quote">&quot;I don&apos;t solve problems, I incinerate them&quot;</p><section><label>Preferences</label><button className="edit-button" title="Edit preferences"><Pencil size={13}/></button><div className="profile-chips">{['TS','JS','HTML','CSS'].map((item) => <span key={item}>{item}</span>)}</div></section><section><label>Contribution badges</label><div className="profile-chips"><span>10</span><span>25</span></div></section><div className="profile-level"><span>Level&nbsp;&nbsp;26</span><div><small>19</small><i style={{width:`${profile.progress_score}%`}}/><small>75</small></div></div></aside>
    </section>
    {selected && <div className="web-modal" role="dialog" aria-modal="true"><article className="web-modal-card"><button className="modal-close" onClick={() => setSelected(null)} title="Close"><X size={18}/></button><span className={`difficulty ${selected.difficulty.toLowerCase()}`}>{selected.difficulty} · {selected.difficulty_score}/10</span><h2>{selected.title}</h2><p className="modal-repo">{selected.repository}</p><p className="modal-body">{selected.body}</p><div className="atom-row">{selected.required_skills.map((skill) => <span className="atom" key={skill}>{skill}</span>)}</div><div className="modal-actions"><a href={selected.url} target="_blank">Open on GitHub ↗</a><button className="start-button" onClick={startChallenge}>Start challenge <ChevronDown size={14}/></button></div></article></div>}
  </main>;
}

import { createRoot } from 'react-dom/client';
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
